FROM georchestra/security-proxy

RUN echo "urbanisme=http://urbanisme:8080/urbanisme/"   >> /etc/georchestra/security-proxy/targets-mapping.properties
RUN echo "cadastrapp=http://cadastrapp:8080/cadastrapp/" >> /etc/georchestra/security-proxy/targets-mapping.properties

