throwErrorOnExtraParameters: false

templates:
  A4 portrait: !template
    reportTemplate: A4_Portrait.jrxml
    attributes:
      parcelle: !string {}
      commune: !string {}
      codeSection: !string {}
      numero: !string {}
      adresseCadastrale: !string {}
      contenanceDGFiP: !string {}
      surfaceSIG: !string {}
      codeProprio: !string {}
      nomProprio: !string {}
      adresseProprio: !string {}
      dateRU: !string {}
      datePCI: !string {}
      libelles: !string
        default: ""
      mapImageStream: !string
        default: ""
      adressesPostales: !string
        default: ""
      intra: !boolean
        default: false
      libelles_1: !string
        default: ""
      libelles_2: !string
        default: ""
      libelles_311: !string
        default: ""
      libelles_312: !string
        default: ""
      libelles_313: !string
        default: ""
      libelles_314: !string
        default: ""
      libelles_315: !string
        default: ""
      libelles_32: !string
        default: ""
      libelles_33: !string
        default: ""
      libelles_4: !string
        default: ""
      libelles_5: !string
        default: ""
      libelles_6: !string
        default: ""
      libelles_7: !string
        default: ""
      libelles_alertes: !string
        default: ""
      legendURL: !string
        default: ""
      map: !map
        maxDpi: 254
        width: 555
        height: 280
    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !configureHttpRequests
        httpProcessors:
          - !addHeaders
            headers:
              User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
      - !createMap {}

  A4 portrait ADS: !template
    reportTemplate: A4_Portrait_ADS.jrxml
    attributes:
      parcelle: !string {}
      instruction: !string {}
      numNom: !string {}
      numDossier: !string {}
      legendURL: !string
        default: ""
      map: !map
        maxDpi: 254
        width: 555
        height: 280
    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !configureHttpRequests
        httpProcessors:
          - !addHeaders
            headers:
              User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
      - !createMap {}

  A4 portrait PLUi: !template
    reportTemplate: A4_Portrait_PLUi.jrxml
    attributes:
      parcelle: !string { }
      commune: !string { }
      codeSection: !string { }
      numero: !string { }
      adresseCadastrale: !string { }
      contenanceDGFiP: !string { }
      surfaceSIG: !string { }
      codeProprio: !string { }
      nomProprio: !string { }
      adresseProprio: !string { }
      dateRU: !string { }
      datePCI: !string { }
      libelles: !string
        default: ""
      mapImageStream: !string
        default: ""
      adressesPostales: !string
        default: ""
      intra: !boolean
        default: false
      libelles_1: !string
        default: ""
      libelles_2: !string
        default: ""
      libelles_311: !string
        default: ""
      libelles_312: !string
        default: ""
      libelles_313: !string
        default: ""
      libelles_314: !string
        default: ""
      libelles_315: !string
        default: ""
      libelles_32: !string
        default: ""
      libelles_33: !string
        default: ""
      libelles_4: !string
        default: ""
      libelles_5: !string
        default: ""
      libelles_6: !string
        default: ""
      libelles_7: !string
        default: ""
      libelles_alertes: !string
        default: ""
      typeDocument: !string { }
      legendURL: !string
        default: ""
      map: !map
        maxDpi: 254
        width: 555
        height: 280
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !configureHttpRequests
      httpProcessors:
        - !addHeaders
          headers:
            User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
    - !createMap { }

  A4 portrait PSMV: !template
    reportTemplate: A4_Portrait_PSMV.jrxml
    attributes:
      parcelle: !string { }
      commune: !string { }
      codeSection: !string { }
      numero: !string { }
      adresseCadastrale: !string { }
      contenanceDGFiP: !string { }
      surfaceSIG: !string { }
      codeProprio: !string { }
      nomProprio: !string { }
      adresseProprio: !string { }
      dateRU: !string { }
      datePCI: !string { }
      libelles: !string
        default: ""
      mapImageStream: !string
        default: ""
      adressesPostales: !string
        default: ""
      intra: !boolean
        default: false
      libelles_1: !string
        default: ""
      libelles_2: !string
        default: ""
      libelles_311: !string
        default: ""
      libelles_312: !string
        default: ""
      libelles_313: !string
        default: ""
      libelles_314: !string
        default: ""
      libelles_315: !string
        default: ""
      libelles_32: !string
        default: ""
      libelles_33: !string
        default: ""
      libelles_4: !string
        default: ""
      libelles_5: !string
        default: ""
      libelles_6: !string
        default: ""
      libelles_7: !string
        default: ""
      libelles_alertes: !string
        default: ""
      typeDocument: !string { }
      legendURL: !string
        default: ""
      map: !map
        maxDpi: 254
        width: 555
        height: 280
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !configureHttpRequests
      httpProcessors:
        - !addHeaders
          headers:
            User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0"
    - !createMap { }
