name: "builds a addon_urbanisme docker image"
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checking out"
        uses: actions/checkout@v2

      - name: "builds the docker image"
        run: |
          mvn clean package
          cd target/docker/urbanisme && docker build -t sigrennesmetropole/addon_urbanisme:latest .

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to docker-hub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "pushes the docker image"
        run: |
          docker push sigrennesmetropole/addon_urbanisme:latest
